In [1]:
%run ./../../utils/commonImports.py
%run ./../../utils/tradingImports.py
%matplotlib inline

# Load Data

In [2]:
def load_and_divide(db, table, from_date=None, to_date=None, train_ratio=0.5, period=None):
    data = load_trading_data(db, table, from_date, to_date, period)
    data_train, data_test = divide_train_and_test(data, train_ratio)
    return data, data_train, data_test


db = 'D:\\Dropbox\\My work\\krypl-project\\sqlite\\ploniex-chart-data\\USDT_BTC.db'
data, data_train, data_test = load_and_divide(db, 'chart_data', from_date='2014-01-01', period='5min')
ohlc, ohlc_train, ohlc_test = data.copy(), data_train.copy(), data_test.copy()

In [4]:
data.head()

,timestamp,period,open,high,low,close,volume,quoteVolume,weightedAverage,date
1,1424372400,5min,225.0000,225.0000,225.0000,225.0000,1.0000,0.0044,225.0000,2015-02-19 20:00:00
2,1424373000,5min,225.0000,225.0000,225.0000,225.0000,1.0000,0.0044,225.0000,2015-02-19 20:10:00
3,1424373300,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:15:00
4,1424373600,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:20:00
5,1424373900,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:25:00

# Experiment

Celý experiment spočívá v olabelovaní dat následujícím způsobem. Pokud daný bod při nákupu vydělá více než 1% tak True.
Snaha bude naučit klasifikátor tak, aby měl co nejlepší precision a zároveň provedl co nejvíce obchodů.

# Calculation

In [13]:
import time

maxs = []
till_maxs = []
mins = []
df = ohlc.copy()
DAY = 288
TARGET = 0.01

def _max_row(day_df, col):
    i = day_df[col].idxmax()
    max_row = day_df.iloc[i, :]
    return max_row

def _min_row(day_df, col):
    i = day_df[col].idxmin()
    min_row = day_df.iloc[i, :]
    return min_row

def _max(day_df):
    close_max_row = _max_row(day_df, 'close')
    open_max_row = _max_row(day_df, 'open')
    return (close_max_row, 'close') if close_max_row['close'] > open_max_row['open'] else (open_max_row, 'open')

def _fullfiled_row(row, day_df, col, target):
    day_df['R'] = _return(row['close'], day_df[col])
    fullfiled = day_df.query(f"R >= {target}")
    if fullfiled.shape[0] > 0:
        return fullfiled.iloc[0, :]
    else:
        return day_df.iloc[-1, :]

def fullfiled(row, day_df, target):
    close_row = _fullfiled_row(row, day_df, 'close', target)
    open_row = _fullfiled_row(row, day_df, 'open', target)
    return (close_row, 'close') if close_row['close'] > open_row['open'] else (open_row, 'open')

def _return(v1, v2):
    return (v2 / v1) - 1


start_time = time.time()
for i in range(df.shape[0] - 1):
    if i % 1000 == 0:
        print(i, '%.3f s' % (time.time() - start_time))
        start_time = time.time()
    
    day_i = i + DAY if i + DAY < df.shape[0] else df.shape[0]-1
    row = df.iloc[i, :]
    day_df = df.iloc[i+1:day_i, :].reset_index().drop('index', axis=1).reset_index()

    
    fullfiled_row, fullfiled_col = fullfiled(row, day_df, TARGET)
    
    max_index = fullfiled_row['index'] if fullfiled_row['index'] > 0 else 1
    day_df = day_df.iloc[:max_index, :]
    min_row = _min_row(day_df, 'low')
    
    maxs.append(_return(row['close'], fullfiled_row[fullfiled_col]))
    till_maxs.append(fullfiled_row['index'])
    mins.append(_return(row['close'], min_row['low']))

0 0.001 s
1000 10.664 s
2000 9.985 s
3000 9.910 s
4000 10.110 s
5000 10.306 s
6000 9.965 s
7000 10.074 s
8000 10.945 s
9000 10.216 s
10000 9.949 s
11000 11.019 s
12000 10.188 s
13000 9.968 s
14000 9.921 s
15000 10.669 s
16000 10.459 s
17000 12.183 s
18000 11.687 s
19000 12.552 s
20000 10.233 s
21000 9.944 s
22000 10.271 s
23000 10.266 s
24000 9.841 s
25000 9.816 s
26000 9.729 s
27000 9.782 s
28000 10.233 s
29000 10.986 s
30000 10.947 s
31000 9.925 s
32000 9.831 s
33000 9.990 s
34000 9.881 s
35000 9.973 s
36000 9.869 s
37000 9.871 s
38000 10.605 s
39000 9.860 s
40000 9.885 s
41000 9.911 s
42000 9.814 s
43000 9.826 s
44000 9.828 s
45000 9.839 s
46000 9.865 s
47000 9.816 s
48000 9.881 s
49000 9.851 s
50000 9.877 s
51000 9.859 s
52000 9.949 s
53000 9.990 s
54000 9.838 s
55000 9.820 s
56000 9.854 s
57000 9.834 s
58000 9.855 s
59000 9.858 s
60000 9.828 s
61000 9.805 s
62000 9.775 s
63000 9.865 s
64000 10.408 s
65000 9.835 s
66000 9.796 s
67000 9.922 s
68000 11.287 s
69000 10.047 s
70000 11.480 s
71000 9.913 s
72000 9.852 s
73000 9.844 s
74000 9.898 s
75000 9.917 s
76000 10.014 s
77000 9.889 s
78000 9.800 s
79000 9.822 s
80000 9.787 s
81000 9.812 s
82000 9.819 s
83000 10.833 s
84000 13.252 s
85000 9.993 s
86000 9.833 s
87000 9.800 s
88000 9.781 s
89000 9.909 s
90000 9.877 s
91000 9.822 s
92000 9.812 s
93000 9.831 s
94000 9.802 s
95000 9.770 s
96000 9.842 s
97000 9.804 s
98000 10.093 s
99000 9.861 s
100000 9.843 s
101000 9.874 s
102000 9.861 s
103000 9.795 s
104000 9.828 s
105000 9.803 s
106000 9.833 s
107000 10.078 s
108000 9.836 s
109000 9.807 s
110000 9.816 s
111000 9.817 s
112000 9.824 s
113000 9.821 s
114000 9.820 s
115000 9.874 s
116000 9.734 s
117000 9.726 s
118000 9.791 s
119000 9.924 s
120000 10.150 s
121000 9.846 s
122000 9.791 s
123000 9.817 s
124000 9.841 s
125000 9.802 s
126000 9.829 s
127000 9.910 s
128000 10.326 s
129000 9.805 s
130000 9.797 s
131000 9.771 s
132000 9.800 s
133000 9.828 s
134000 9.841 s
135000 9.813 s
136000 9.808 s
137000 9.773 s
138000 9.857 s
139000 9.837 s
140000 9.867 s
141000 9.867 s
142000 9.832 s
143000 9.769 s
144000 9.884 s
145000 9.781 s
146000 9.764 s
147000 9.807 s
148000 9.810 s
149000 9.794 s
150000 9.779 s
151000 9.819 s
152000 9.793 s
153000 9.818 s
154000 9.932 s
155000 9.769 s
156000 9.763 s
157000 9.836 s
158000 9.838 s
159000 10.295 s
160000 9.813 s
161000 9.804 s
162000 9.901 s
163000 9.797 s
164000 9.837 s
165000 9.796 s
166000 9.790 s
167000 9.739 s
168000 9.827 s
169000 9.696 s
170000 9.735 s
171000 9.738 s
172000 9.753 s
173000 9.750 s
174000 9.759 s
175000 9.806 s
176000 9.802 s
177000 9.781 s
178000 9.765 s
179000 9.748 s
180000 9.794 s
181000 9.862 s
182000 9.751 s
183000 9.750 s
184000 9.799 s
185000 9.893 s
186000 9.734 s
187000 9.810 s
188000 9.880 s
189000 10.047 s
190000 9.843 s
191000 9.786 s
192000 9.751 s
193000 9.821 s
194000 9.969 s
195000 9.759 s
196000 9.732 s
197000 9.839 s
198000 9.854 s
199000 9.790 s
200000 9.841 s
201000 9.802 s
202000 9.794 s
203000 9.748 s
204000 9.781 s
205000 9.719 s
206000 9.787 s
207000 9.900 s
208000 9.745 s
209000 9.808 s
210000 9.758 s
211000 9.893 s
212000 9.939 s
213000 9.843 s
214000 10.110 s
215000 10.015 s
216000 9.881 s
217000 9.887 s
218000 9.803 s
219000 9.858 s
220000 10.315 s
221000 9.864 s
222000 9.768 s
223000 9.796 s
224000 9.781 s
225000 10.957 s
226000 9.786 s
227000 9.788 s
228000 9.788 s
229000 10.603 s
230000 10.561 s
231000 15.000 s
232000 13.335 s
233000 11.645 s
234000 17.593 s
235000 12.641 s
236000 12.690 s
237000 13.090 s
238000 14.187 s
239000 15.362 s
240000 14.896 s
241000 18.757 s
242000 13.650 s
243000 13.500 s
244000 16.689 s
245000 13.256 s
246000 12.900 s
247000 12.930 s
248000 14.494 s
249000 13.488 s
250000 13.410 s
251000 13.908 s
252000 15.687 s
253000 14.805 s
254000 14.894 s
255000 13.911 s
256000 13.360 s
257000 15.613 s
258000 15.220 s
259000 14.172 s
260000 13.369 s
261000 15.158 s
262000 13.760 s
263000 14.329 s
264000 15.236 s
265000 14.510 s
266000 11.775 s
267000 11.544 s
268000 11.464 s
269000 11.771 s
270000 11.892 s
271000 11.443 s
272000 13.411 s
273000 12.490 s
274000 11.578 s
275000 11.453 s
276000 11.700 s
277000 11.903 s
278000 11.750 s
279000 16.588 s
280000 11.388 s
281000 17.705 s
282000 17.135 s
283000 16.000 s
284000 17.952 s
285000 17.449 s
286000 14.727 s
287000 13.910 s
288000 15.306 s
289000 18.045 s
290000 13.953 s
291000 15.125 s
292000 14.319 s
293000 15.006 s
294000 14.419 s
295000 14.000 s
296000 13.710 s
297000 13.622 s
298000 13.608 s
299000 15.704 s
300000 15.422 s
301000 15.905 s
302000 13.683 s
303000 17.469 s
304000 14.102 s
305000 14.234 s
306000 14.135 s
307000 14.695 s
308000 14.205 s
309000 13.816 s
310000 14.825 s
311000 14.429 s
312000 13.642 s
313000 15.308 s
314000 14.154 s
315000 14.283 s
316000 15.132 s
317000 14.016 s
318000 11.172 s
319000 10.342 s
320000 10.260 s
321000 10.344 s
322000 11.294 s
323000 12.419 s
324000 13.414 s
325000 12.962 s
326000 11.883 s
327000 12.054 s
328000 14.607 s
329000 15.896 s
330000 18.121 s
331000 14.610 s
332000 14.594 s
333000 15.179 s
334000 15.674 s
335000 16.477 s
336000 18.085 s
337000 16.682 s
338000 14.686 s
339000 12.594 s
340000 12.958 s
341000 12.111 s
342000 14.150 s
343000 11.966 s
344000 11.885 s
345000 14.101 s
346000 17.062 s
347000 15.818 s
348000 15.472 s
349000 12.880 s
350000 14.101 s
351000 13.699 s
352000 22.051 s
353000 14.956 s
354000 14.363 s
355000 13.220 s
356000 13.164 s
357000 13.885 s
358000 13.760 s
359000 13.210 s
360000 13.865 s

IndexError: single positional indexer is out-of-bounds

In [14]:
maxs += [-1, -1]
till_maxs += [-1, -1]
mins += [-1, -1]

In [15]:
df = ohlc.copy()
df['maxReturn'] = maxs
df['tillMax'] = till_maxs
df['minReturn'] = mins

In [16]:
df

,timestamp,period,open,high,low,close,volume,quoteVolume,weightedAverage,date,maxReturn,tillMax,minReturn
1,1424372400,5min,225.0000,225.0000,225.0000,225.0000,1.0000,0.0044,225.0000,2015-02-19 20:00:00,0.0667,15,0.0000
2,1424373000,5min,225.0000,225.0000,225.0000,225.0000,1.0000,0.0044,225.0000,2015-02-19 20:10:00,0.0667,14,0.0000
3,1424373300,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:15:00,0.0667,13,0.0000
4,1424373600,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:20:00,0.0667,12,0.0000
5,1424373900,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:25:00,0.0667,11,0.0000
7,1424374200,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:30:00,0.0667,10,0.0000
8,1424374500,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:35:00,0.0667,9,0.0000
9,1424374800,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:40:00,0.0667,8,0.0000
10,1424375100,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:45:00,0.0667,7,0.0000
11,1424375400,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:50:00,0.0667,6,0.0000
12,1424375700,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:55:00,0.0667,5,0.0000
13,1424376000,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 21:00:00,0.0667,4,0.0000
15,1424376300,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 21:05:00,0.0667,3,0.0000
16,1424376600,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 21:10:00,0.0667,2,0.0000
17,1424376900,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 21:15:00,0.0667,1,0.0000
18,1424377200,5min,225.0000,240.0000,225.0000,240.0000,30.6247,0.1286,238.0921,2015-02-19 21:20:00,0.0167,4,0.0000
19,1424377500,5min,240.0000,240.0000,240.0000,240.0000,0.0000,0.0000,240.0000,2015-02-19 21:25:00,0.0167,3,0.0000
20,1424377800,5min,240.0000,240.0000,240.0000,240.0000,0.0000,0.0000,240.0000,2015-02-19 21:30:00,0.0167,2,0.0000
22,1424378100,5min,240.0000,240.0000,240.0000,240.0000,0.0000,0.0000,240.0000,2015-02-19 21:35:00,0.0167,1,0.0000
23,1424378400,5min,240.0000,240.0000,240.0000,240.0000,0.0000,0.0000,240.0000,2015-02-19 21:40:00,0.0167,0,0.0167
24,1424378700,5min,244.0000,244.0000,244.0000,244.0000,14.6512,0.0600,244.0000,2015-02-19 21:45:00,-0.0154,286,-0.0154
25,1424379000,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 21:50:00,-0.0154,286,-0.0154
26,1424379300,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 21:55:00,-0.0154,286,-0.0154
27,1424379600,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:00:00,-0.0154,286,-0.0154
29,1424379900,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:05:00,-0.0154,286,-0.0154
30,1424380200,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:10:00,-0.0154,286,-0.0154
31,1424380500,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:15:00,-0.0154,286,-0.0154
32,1424380800,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:20:00,-0.0154,286,-0.0154
33,1424381100,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:25:00,-0.0154,286,-0.0154
35,1424381400,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:30:00,-0.0154,286,-0.0154
...,...,...,...,...,...,...,...,...,...,...,...,...,...
417911,1537155000,5min,"6,512.6037","6,518.9424","6,510.4133","6,518.8800","19,961.3750",3.0644,"6,513.9777",2018-09-17 05:30:00,-0.0355,27,-0.0479
417912,1537156800,5min,"6,513.7462","6,513.7462","6,473.6942","6,485.2671","83,629.6560",12.8905,"6,487.7179",2018-09-17 06:00:00,-0.0305,26,-0.0429
417913,1537158600,5min,"6,485.2671","6,494.7381","6,473.8517","6,476.2640","19,542.5087",3.0124,"6,487.3859",2018-09-17 06:30:00,-0.0291,25,-0.0416
417914,1537160400,5min,"6,473.3844","6,485.6598","6,464.0000","6,468.0583","58,353.3563",9.0120,"6,475.0448",2018-09-17 07:00:00,-0.0279,24,-0.0404
417915,1537162200,5min,"6,471.3409","6,485.2031","6,471.3409","6,484.0000","38,779.6653",5.9862,"6,478.1866",2018-09-17 07:30:00,-0.0303,23,-0.0428
417916,1537164000,5min,"6,484.6484","6,484.8600","6,471.3499","6,477.2463","53,418.9421",8.2472,"6,477.1967",2018-09-17 08:00:00,-0.0293,22,-0.0418
417917,1537165800,5min,"6,481.3574","6,489.0898","6,479.1980","6,485.0000","66,913.5507",10.3178,"6,485.2772",2018-09-17 08:30:00,-0.0305,21,-0.0429
417918,1537167600,5min,"6,485.0000","6,485.0000","6,462.2300","6,467.1253","40,673.7036",6.2908,"6,465.5693",2018-09-17 09:00:00,-0.0278,20,-0.0403
417919,1537169400,5min,"6,464.1297","6,479.3559","6,464.0982","6,479.3559","9,848.6063",1.5224,"6,469.1397",2018-09-17 09:30:00,-0.0296,19,-0.0421
417920,1537171200,5min,"6,479.3559","6,479.3559","6,465.0000","6,467.9485","138,289.8007",21.3750,"6,469.6961",2018-09-17 10:00:00,-0.0279,18,-0.0404
417921,1537173000,5min,"6,472.1254","6,475.6374","6,465.0000","6,470.8828","328,181.1689",50.7300,"6,469.1728",2018-09-17 10:30:00,-0.0283,17,-0.0408
417922,1537174800,5min,"6,470.8828","6,496.9116","6,415.6834","6,487.8435","455,561.9720",70.6256,"6,450.3793",2018-09-17 11:00:00,-0.0309,16,-0.0433
417923,1537176600,5min,"6,486.3471","6,500.0000","6,482.6628","6,489.8480","39,259.4071",6.0494,"6,489.8424",2018-09-17 11:30:00,-0.0312,15,-0.0436
417924,1537178400,5min,"6,494.2656","6,500.0000","6,486.5100","6,491.9000","23,115.7933",3.5595,"6,494.1487",2018-09-17 12:00:00,-0.0315,14,-0.0439
417925,1537180200,5min,"6,491.0000","6,491.0000","6,471.8937","6,477.2770","11,226.7478",1.7309,"6,485.9194",2018-09-17 12:30:00,-0.0293,13,-0.0418
417926,1537182000,5min,"6,471.8937","6,490.4163","6,471.8937","6,481.4076","7,080.5995",1.0925,"6,481.2984",2018-09-17 13:00:00,-0.0299,12,-0.0424
417927,1537183800,5min,"6,481.4076","6,485.0000","6,471.5125","6,472.2554","14,011.4280",2.1625,"6,479.2199",2018-09-17 13:30:00,-0.0285,11,-0.0410
417928,1537185600,5min,"6,474.5463","6,474.5463","6,440.5999","6,453.1824","41,010.6229",6.3551,"6,453.1923",2018-09-17 14:00:00,-0.0257,10,-0.0382
417929,1537187400,5min,"6,453.1824","6,464.0000","6,451.0000","6,452.1385","62,789.8786",9.7252,"6,456.3908",2018-09-17 14:30:00,-0.0255,9,-0.0380
417930,1537189200,5min,"6,450.3549","6,455.0986","6,440.0415","6,453.3788","81,668.6223",12.6705,"6,445.5580",2018-09-17 15:00:00,-0.0257,8,-0.0382
417931,1537191000,5min,"6,451.3349","6,451.3349","6,390.0000","6,418.8161","227,210.1904",35.4331,"6,412.3644",2018-09-17 15:30:00,-0.0205,7,-0.0330
417932,1537192800,5min,"6,418.8161","6,419.3109","6,316.1571","6,345.2554","728,248.1980",114.5581,"6,357.0204",2018-09-17 16:00:00,-0.0091,6,-0.0218
417933,1537194600,5min,"6,341.5565","6,369.2734","6,335.1291","6,349.7587","172,906.9525",27.2283,"6,350.2720",2018-09-17 16:30:00,-0.0098,5,-0.0225
417934,1537196400,5min,"6,352.7074","6,352.7074","6,206.7604","6,260.0000","803,780.2587",128.5143,"6,254.4013",2018-09-17 17:00:00,0.0044,4,-0.0057
417935,1537198200,5min,"6,262.5629","6,273.2025","6,224.5000","6,261.3700","234,700.1428",37.5431,"6,251.4862",2018-09-17 17:30:00,0.0042,3,0.0000
417936,1537200000,5min,"6,262.5732","6,297.0000","6,261.3700","6,271.7090","270,698.0516",43.1399,"6,274.8847",2018-09-17 18:00:00,0.0025,2,-0.0016
417937,1537201800,5min,"6,281.3373","6,288.7958","6,261.7439","6,261.7439","68,021.9392",10.8351,"6,277.9357",2018-09-17 18:30:00,0.0041,1,-0.0001
417938,1537203600,5min,"6,265.7089","6,280.0000","6,261.3810","6,272.3441","173,722.7871",27.6974,"6,272.1613",2018-09-17 19:00:00,0.0024,0,-0.0011
417939,1537205400,5min,"6,265.5379","6,289.0655","6,265.5200","6,287.4922","118,713.2179",18.8961,"6,282.4313",2018-09-17 19:30:00,-1.0000,-1,-1.0000
417940,1537207200,5min,"6,289.1695","6,316.6496","6,289.1695","6,308.0809","78,169.3516",12.3915,"6,308.3133",2018-09-17 20:00:00,-1.0000,-1,-1.0000

In [17]:
write_tsv(df, 'D:\\Dropbox\\My work\\krypl-project\\analysis\\return-01-within-day.tsv')