In [1]:
%run ./../../utils/commonImports.py
%run ./../../utils/tradingImports.py
%matplotlib inline

# Make Labels

In [2]:
df = read_tsv('D:\\Dropbox\\My work\\krypl-project\\analysis\\return-01-within-day.tsv')
df['label'] = (df['maxReturn'] > 0.01) & (df['minReturn'] > -0.01)
write_tsv(df, 'D:\\Dropbox\\My work\\krypl-project\\dataLabeled\\return-01-loss-max-01-within-day.tsv')

In [3]:
df

,timestamp,period,open,high,low,close,volume,quoteVolume,weightedAverage,date,maxReturn,tillMax,minReturn,label
0,1424372400,5min,225.0000,225.0000,225.0000,225.0000,1.0000,0.0044,225.0000,2015-02-19 20:00:00,0.0667,15,0.0000,True
1,1424373000,5min,225.0000,225.0000,225.0000,225.0000,1.0000,0.0044,225.0000,2015-02-19 20:10:00,0.0667,14,0.0000,True
2,1424373300,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:15:00,0.0667,13,0.0000,True
3,1424373600,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:20:00,0.0667,12,0.0000,True
4,1424373900,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:25:00,0.0667,11,0.0000,True
5,1424374200,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:30:00,0.0667,10,0.0000,True
6,1424374500,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:35:00,0.0667,9,0.0000,True
7,1424374800,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:40:00,0.0667,8,0.0000,True
8,1424375100,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:45:00,0.0667,7,0.0000,True
9,1424375400,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:50:00,0.0667,6,0.0000,True
10,1424375700,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 20:55:00,0.0667,5,0.0000,True
11,1424376000,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 21:00:00,0.0667,4,0.0000,True
12,1424376300,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 21:05:00,0.0667,3,0.0000,True
13,1424376600,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 21:10:00,0.0667,2,0.0000,True
14,1424376900,5min,225.0000,225.0000,225.0000,225.0000,0.0000,0.0000,225.0000,2015-02-19 21:15:00,0.0667,1,0.0000,True
15,1424377200,5min,225.0000,240.0000,225.0000,240.0000,30.6247,0.1286,238.0921,2015-02-19 21:20:00,0.0167,4,0.0000,True
16,1424377500,5min,240.0000,240.0000,240.0000,240.0000,0.0000,0.0000,240.0000,2015-02-19 21:25:00,0.0167,3,0.0000,True
17,1424377800,5min,240.0000,240.0000,240.0000,240.0000,0.0000,0.0000,240.0000,2015-02-19 21:30:00,0.0167,2,0.0000,True
18,1424378100,5min,240.0000,240.0000,240.0000,240.0000,0.0000,0.0000,240.0000,2015-02-19 21:35:00,0.0167,1,0.0000,True
19,1424378400,5min,240.0000,240.0000,240.0000,240.0000,0.0000,0.0000,240.0000,2015-02-19 21:40:00,0.0167,0,0.0167,True
20,1424378700,5min,244.0000,244.0000,244.0000,244.0000,14.6512,0.0600,244.0000,2015-02-19 21:45:00,-0.0154,286,-0.0154,False
21,1424379000,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 21:50:00,-0.0154,286,-0.0154,False
22,1424379300,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 21:55:00,-0.0154,286,-0.0154,False
23,1424379600,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:00:00,-0.0154,286,-0.0154,False
24,1424379900,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:05:00,-0.0154,286,-0.0154,False
25,1424380200,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:10:00,-0.0154,286,-0.0154,False
26,1424380500,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:15:00,-0.0154,286,-0.0154,False
27,1424380800,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:20:00,-0.0154,286,-0.0154,False
28,1424381100,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:25:00,-0.0154,286,-0.0154,False
29,1424381400,5min,244.0000,244.0000,244.0000,244.0000,0.0000,0.0000,244.0000,2015-02-19 22:30:00,-0.0154,286,-0.0154,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360262,1537155000,5min,"6,512.6037","6,518.9424","6,510.4133","6,518.8800","19,961.3750",3.0644,"6,513.9777",2018-09-17 05:30:00,-0.0355,27,-0.0479,False
360263,1537156800,5min,"6,513.7462","6,513.7462","6,473.6942","6,485.2671","83,629.6560",12.8905,"6,487.7179",2018-09-17 06:00:00,-0.0305,26,-0.0429,False
360264,1537158600,5min,"6,485.2671","6,494.7381","6,473.8517","6,476.2640","19,542.5087",3.0124,"6,487.3859",2018-09-17 06:30:00,-0.0291,25,-0.0416,False
360265,1537160400,5min,"6,473.3844","6,485.6598","6,464.0000","6,468.0583","58,353.3563",9.0120,"6,475.0448",2018-09-17 07:00:00,-0.0279,24,-0.0404,False
360266,1537162200,5min,"6,471.3409","6,485.2031","6,471.3409","6,484.0000","38,779.6653",5.9862,"6,478.1866",2018-09-17 07:30:00,-0.0303,23,-0.0428,False
360267,1537164000,5min,"6,484.6484","6,484.8600","6,471.3499","6,477.2463","53,418.9421",8.2472,"6,477.1967",2018-09-17 08:00:00,-0.0293,22,-0.0418,False
360268,1537165800,5min,"6,481.3574","6,489.0898","6,479.1980","6,485.0000","66,913.5507",10.3178,"6,485.2772",2018-09-17 08:30:00,-0.0305,21,-0.0429,False
360269,1537167600,5min,"6,485.0000","6,485.0000","6,462.2300","6,467.1253","40,673.7036",6.2908,"6,465.5693",2018-09-17 09:00:00,-0.0278,20,-0.0403,False
360270,1537169400,5min,"6,464.1297","6,479.3559","6,464.0982","6,479.3559","9,848.6063",1.5224,"6,469.1397",2018-09-17 09:30:00,-0.0296,19,-0.0421,False
360271,1537171200,5min,"6,479.3559","6,479.3559","6,465.0000","6,467.9485","138,289.8007",21.3750,"6,469.6961",2018-09-17 10:00:00,-0.0279,18,-0.0404,False
360272,1537173000,5min,"6,472.1254","6,475.6374","6,465.0000","6,470.8828","328,181.1689",50.7300,"6,469.1728",2018-09-17 10:30:00,-0.0283,17,-0.0408,False
360273,1537174800,5min,"6,470.8828","6,496.9116","6,415.6834","6,487.8435","455,561.9720",70.6256,"6,450.3793",2018-09-17 11:00:00,-0.0309,16,-0.0433,False
360274,1537176600,5min,"6,486.3471","6,500.0000","6,482.6628","6,489.8480","39,259.4071",6.0494,"6,489.8424",2018-09-17 11:30:00,-0.0312,15,-0.0436,False
360275,1537178400,5min,"6,494.2656","6,500.0000","6,486.5100","6,491.9000","23,115.7933",3.5595,"6,494.1487",2018-09-17 12:00:00,-0.0315,14,-0.0439,False
360276,1537180200,5min,"6,491.0000","6,491.0000","6,471.8937","6,477.2770","11,226.7478",1.7309,"6,485.9194",2018-09-17 12:30:00,-0.0293,13,-0.0418,False
360277,1537182000,5min,"6,471.8937","6,490.4163","6,471.8937","6,481.4076","7,080.5995",1.0925,"6,481.2984",2018-09-17 13:00:00,-0.0299,12,-0.0424,False
360278,1537183800,5min,"6,481.4076","6,485.0000","6,471.5125","6,472.2554","14,011.4280",2.1625,"6,479.2199",2018-09-17 13:30:00,-0.0285,11,-0.0410,False
360279,1537185600,5min,"6,474.5463","6,474.5463","6,440.5999","6,453.1824","41,010.6229",6.3551,"6,453.1923",2018-09-17 14:00:00,-0.0257,10,-0.0382,False
360280,1537187400,5min,"6,453.1824","6,464.0000","6,451.0000","6,452.1385","62,789.8786",9.7252,"6,456.3908",2018-09-17 14:30:00,-0.0255,9,-0.0380,False
360281,1537189200,5min,"6,450.3549","6,455.0986","6,440.0415","6,453.3788","81,668.6223",12.6705,"6,445.5580",2018-09-17 15:00:00,-0.0257,8,-0.0382,False
360282,1537191000,5min,"6,451.3349","6,451.3349","6,390.0000","6,418.8161","227,210.1904",35.4331,"6,412.3644",2018-09-17 15:30:00,-0.0205,7,-0.0330,False
360283,1537192800,5min,"6,418.8161","6,419.3109","6,316.1571","6,345.2554","728,248.1980",114.5581,"6,357.0204",2018-09-17 16:00:00,-0.0091,6,-0.0218,False
360284,1537194600,5min,"6,341.5565","6,369.2734","6,335.1291","6,349.7587","172,906.9525",27.2283,"6,350.2720",2018-09-17 16:30:00,-0.0098,5,-0.0225,False
360285,1537196400,5min,"6,352.7074","6,352.7074","6,206.7604","6,260.0000","803,780.2587",128.5143,"6,254.4013",2018-09-17 17:00:00,0.0044,4,-0.0057,False
360286,1537198200,5min,"6,262.5629","6,273.2025","6,224.5000","6,261.3700","234,700.1428",37.5431,"6,251.4862",2018-09-17 17:30:00,0.0042,3,0.0000,False
360287,1537200000,5min,"6,262.5732","6,297.0000","6,261.3700","6,271.7090","270,698.0516",43.1399,"6,274.8847",2018-09-17 18:00:00,0.0025,2,-0.0016,False
360288,1537201800,5min,"6,281.3373","6,288.7958","6,261.7439","6,261.7439","68,021.9392",10.8351,"6,277.9357",2018-09-17 18:30:00,0.0041,1,-0.0001,False
360289,1537203600,5min,"6,265.7089","6,280.0000","6,261.3810","6,272.3441","173,722.7871",27.6974,"6,272.1613",2018-09-17 19:00:00,0.0024,0,-0.0011,False
360290,1537205400,5min,"6,265.5379","6,289.0655","6,265.5200","6,287.4922","118,713.2179",18.8961,"6,282.4313",2018-09-17 19:30:00,-1.0000,-1,-1.0000,False
360291,1537207200,5min,"6,289.1695","6,316.6496","6,289.1695","6,308.0809","78,169.3516",12.3915,"6,308.3133",2018-09-17 20:00:00,-1.0000,-1,-1.0000,False